name: signserial
version: 0.1
summary: Signserial utility
description: Utitlity for signing serial assertion
confinement: devmode

apps:
    signserial:
      command: bin/signserial

parts:
    # signseral:
        # plugin: go
        # source: git://github.com/Lyncore/ubuntu-recovery-image
        # go-importpath: github.com/ubuntu-core/identity-vault
    signserial:
        source: .
        plugin: copy
        files:
          signserial: bin/signserial
